apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hugo-stc
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer