apiVersion: v1
kind: PersistentVolume
metadata:
  name: hugo-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: hugo-stc
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /bavulsite
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/role
          operator: In
          values:
          - worker