// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.17.3
// source: vuln.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	VulnService_AddCVE_FullMethodName        = "/messages.VulnService/AddCVE"
	VulnService_GetCVE_FullMethodName        = "/messages.VulnService/GetCVE"
	VulnService_GetAllCVEs_FullMethodName    = "/messages.VulnService/GetAllCVEs"
	VulnService_DeleteCVE_FullMethodName     = "/messages.VulnService/DeleteCVE"
	VulnService_UpdateCVE_FullMethodName     = "/messages.VulnService/UpdateCVE"
	VulnService_FetchNVDFeeds_FullMethodName = "/messages.VulnService/FetchNVDFeeds"
)

// VulnServiceClient is the client API for VulnService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VulnServiceClient interface {
	AddCVE(ctx context.Context, in *AddCVERequest, opts ...grpc.CallOption) (*CVE, error)
	GetCVE(ctx context.Context, in *GetCVERequest, opts ...grpc.CallOption) (*CVE, error)
	GetAllCVEs(ctx context.Context, in *GetAllCVEsRequest, opts ...grpc.CallOption) (VulnService_GetAllCVEsClient, error)
	DeleteCVE(ctx context.Context, in *DeleteCVERequest, opts ...grpc.CallOption) (*DeleteCVEResponse, error)
	UpdateCVE(ctx context.Context, in *UpdateCVERequest, opts ...grpc.CallOption) (*CVE, error)
	FetchNVDFeeds(ctx context.Context, in *FetchNVDFeedsRequest, opts ...grpc.CallOption) (VulnService_FetchNVDFeedsClient, error)
}

type vulnServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVulnServiceClient(cc grpc.ClientConnInterface) VulnServiceClient {
	return &vulnServiceClient{cc}
}

func (c *vulnServiceClient) AddCVE(ctx context.Context, in *AddCVERequest, opts ...grpc.CallOption) (*CVE, error) {
	out := new(CVE)
	err := c.cc.Invoke(ctx, VulnService_AddCVE_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vulnServiceClient) GetCVE(ctx context.Context, in *GetCVERequest, opts ...grpc.CallOption) (*CVE, error) {
	out := new(CVE)
	err := c.cc.Invoke(ctx, VulnService_GetCVE_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vulnServiceClient) GetAllCVEs(ctx context.Context, in *GetAllCVEsRequest, opts ...grpc.CallOption) (VulnService_GetAllCVEsClient, error) {
	stream, err := c.cc.NewStream(ctx, &VulnService_ServiceDesc.Streams[0], VulnService_GetAllCVEs_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &vulnServiceGetAllCVEsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VulnService_GetAllCVEsClient interface {
	Recv() (*CVE, error)
	grpc.ClientStream
}

type vulnServiceGetAllCVEsClient struct {
	grpc.ClientStream
}

func (x *vulnServiceGetAllCVEsClient) Recv() (*CVE, error) {
	m := new(CVE)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vulnServiceClient) DeleteCVE(ctx context.Context, in *DeleteCVERequest, opts ...grpc.CallOption) (*DeleteCVEResponse, error) {
	out := new(DeleteCVEResponse)
	err := c.cc.Invoke(ctx, VulnService_DeleteCVE_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vulnServiceClient) UpdateCVE(ctx context.Context, in *UpdateCVERequest, opts ...grpc.CallOption) (*CVE, error) {
	out := new(CVE)
	err := c.cc.Invoke(ctx, VulnService_UpdateCVE_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vulnServiceClient) FetchNVDFeeds(ctx context.Context, in *FetchNVDFeedsRequest, opts ...grpc.CallOption) (VulnService_FetchNVDFeedsClient, error) {
	stream, err := c.cc.NewStream(ctx, &VulnService_ServiceDesc.Streams[1], VulnService_FetchNVDFeeds_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &vulnServiceFetchNVDFeedsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VulnService_FetchNVDFeedsClient interface {
	Recv() (*CVE, error)
	grpc.ClientStream
}

type vulnServiceFetchNVDFeedsClient struct {
	grpc.ClientStream
}

func (x *vulnServiceFetchNVDFeedsClient) Recv() (*CVE, error) {
	m := new(CVE)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// VulnServiceServer is the server API for VulnService service.
// All implementations should embed UnimplementedVulnServiceServer
// for forward compatibility
type VulnServiceServer interface {
	AddCVE(context.Context, *AddCVERequest) (*CVE, error)
	GetCVE(context.Context, *GetCVERequest) (*CVE, error)
	GetAllCVEs(*GetAllCVEsRequest, VulnService_GetAllCVEsServer) error
	DeleteCVE(context.Context, *DeleteCVERequest) (*DeleteCVEResponse, error)
	UpdateCVE(context.Context, *UpdateCVERequest) (*CVE, error)
	FetchNVDFeeds(*FetchNVDFeedsRequest, VulnService_FetchNVDFeedsServer) error
}

// UnimplementedVulnServiceServer should be embedded to have forward compatible implementations.
type UnimplementedVulnServiceServer struct {
}

func (UnimplementedVulnServiceServer) AddCVE(context.Context, *AddCVERequest) (*CVE, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCVE not implemented")
}
func (UnimplementedVulnServiceServer) GetCVE(context.Context, *GetCVERequest) (*CVE, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCVE not implemented")
}
func (UnimplementedVulnServiceServer) GetAllCVEs(*GetAllCVEsRequest, VulnService_GetAllCVEsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllCVEs not implemented")
}
func (UnimplementedVulnServiceServer) DeleteCVE(context.Context, *DeleteCVERequest) (*DeleteCVEResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCVE not implemented")
}
func (UnimplementedVulnServiceServer) UpdateCVE(context.Context, *UpdateCVERequest) (*CVE, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCVE not implemented")
}
func (UnimplementedVulnServiceServer) FetchNVDFeeds(*FetchNVDFeedsRequest, VulnService_FetchNVDFeedsServer) error {
	return status.Errorf(codes.Unimplemented, "method FetchNVDFeeds not implemented")
}

// UnsafeVulnServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VulnServiceServer will
// result in compilation errors.
type UnsafeVulnServiceServer interface {
	mustEmbedUnimplementedVulnServiceServer()
}

func RegisterVulnServiceServer(s grpc.ServiceRegistrar, srv VulnServiceServer) {
	s.RegisterService(&VulnService_ServiceDesc, srv)
}

func _VulnService_AddCVE_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCVERequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VulnServiceServer).AddCVE(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VulnService_AddCVE_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VulnServiceServer).AddCVE(ctx, req.(*AddCVERequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VulnService_GetCVE_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCVERequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VulnServiceServer).GetCVE(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VulnService_GetCVE_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VulnServiceServer).GetCVE(ctx, req.(*GetCVERequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VulnService_GetAllCVEs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAllCVEsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VulnServiceServer).GetAllCVEs(m, &vulnServiceGetAllCVEsServer{stream})
}

type VulnService_GetAllCVEsServer interface {
	Send(*CVE) error
	grpc.ServerStream
}

type vulnServiceGetAllCVEsServer struct {
	grpc.ServerStream
}

func (x *vulnServiceGetAllCVEsServer) Send(m *CVE) error {
	return x.ServerStream.SendMsg(m)
}

func _VulnService_DeleteCVE_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCVERequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VulnServiceServer).DeleteCVE(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VulnService_DeleteCVE_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VulnServiceServer).DeleteCVE(ctx, req.(*DeleteCVERequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VulnService_UpdateCVE_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCVERequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VulnServiceServer).UpdateCVE(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VulnService_UpdateCVE_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VulnServiceServer).UpdateCVE(ctx, req.(*UpdateCVERequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VulnService_FetchNVDFeeds_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchNVDFeedsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VulnServiceServer).FetchNVDFeeds(m, &vulnServiceFetchNVDFeedsServer{stream})
}

type VulnService_FetchNVDFeedsServer interface {
	Send(*CVE) error
	grpc.ServerStream
}

type vulnServiceFetchNVDFeedsServer struct {
	grpc.ServerStream
}

func (x *vulnServiceFetchNVDFeedsServer) Send(m *CVE) error {
	return x.ServerStream.SendMsg(m)
}

// VulnService_ServiceDesc is the grpc.ServiceDesc for VulnService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VulnService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "messages.VulnService",
	HandlerType: (*VulnServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddCVE",
			Handler:    _VulnService_AddCVE_Handler,
		},
		{
			MethodName: "GetCVE",
			Handler:    _VulnService_GetCVE_Handler,
		},
		{
			MethodName: "DeleteCVE",
			Handler:    _VulnService_DeleteCVE_Handler,
		},
		{
			MethodName: "UpdateCVE",
			Handler:    _VulnService_UpdateCVE_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllCVEs",
			Handler:       _VulnService_GetAllCVEs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FetchNVDFeeds",
			Handler:       _VulnService_FetchNVDFeeds_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vuln.proto",
}
