apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-svc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: svc
      role: api
  template:
    metadata:
      labels:
        app: svc
        role: api
    spec:
      nodeSelector:
        kubernetes.io/role: worker
      containers:
      - name: api-svc
        image: mtnmunuklu/bavul:v1.0.0
        ports:
        - containerPort: 9000
        command:
        - sh
        - -c
        - /app/apisvc -local=false -auth_addr=$auth_addr -vuln_addr=$vuln_addr
        env:
          - name: auth_addr
            value: auth-service:9001
          - name: vuln_addr
            value: vuln-service:9002
          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: svc-secrets
                key: jwtSecretKey
          - name: CERT_PATH
            valueFrom:
              configMapKeyRef:
                name: svc-configs
                key: certPath
        volumeMounts:
        - name: service-certs
          mountPath: /etc/certs
          readOnly: true
      volumes:
      - name: service-certs
        secret:
          secretName: service-certs
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  ports:
      - protocol: TCP
        port: 9000
        targetPort: 9000
  selector:
    app: svc
    role: api
